import { AxiosResponse } from 'axios'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Tab from '../components/Tab'
import {fetchCatagories} from '../http/index'
import { ICategory, ICollectionResponse } from '../types'

interface IPropTypes{
  categories: {
    items: ICategory[]
  }
}

const Home: NextPage<IPropTypes> = ({categories}) => {
  
  return (
    <div>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      < Tab categories = {categories} name='mubin'/>

      <main >
        <h1 className=' text-3xl font-bold'>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )  
}

export const getServerSideProps: GetServerSideProps = async ()=>{
  //Fetching catagories
  const {data}:AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCatagories()

  return {
    props: {
      categories: {
        items: data.data
      }
    }
  }
}

export default Home
