import { AxiosResponse } from 'axios'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Articals from '../components/Articals'
import Tab from '../components/Tab'
import {fetchArticales, fetchCatagories} from '../http/index'
import { IArtical, ICategory, ICollectionResponse } from '../types'

interface IPropTypes{
  categories: {
    items: ICategory[]
  }
  articales: {
    items: IArtical[]
  }
}

const Home: NextPage<IPropTypes> = ({categories, articales}) => {
  
  return (
    <div>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      < Tab categories = {categories} name='mubin'/>

      <Articals articales= {articales}/>
    </div>
  )  
}

export const getServerSideProps: GetServerSideProps = async ()=>{
  //Fetching catagories
  const {data}:AxiosResponse<ICollectionResponse<ICategory[]>> = await fetchCatagories()

  const {data: articales} :AxiosResponse<ICollectionResponse<IArtical[]>> = await fetchArticales();

  return {
    props: {
      categories: {
        items: data.data,
      },
      articales:{
        items: articales.data
      }
    }
  }
}

export default Home
